Fmt pushl.

diff --git a/scripts/pushl b/scripts/pushl
--- a/scripts/pushl
+++ b/scripts/pushl
@@ -5,12 +5,16 @@
 #   See README.md document in projects page at
 #   https://github.com/stroparo/ds
 
+# ##############################################################################
+# Globals
+
+export PNAME="$(basename "$0")"
 export USAGE="
 NAME
-    pushl - push files to target environments using LFTP program
+    ${PNAME} - push files to target environments using LFTP program
 
 SYNOPSIS
-    pushl $(basename "$0") [-e {env-regex}] [-f {local-globs}] [-p] [-r] {srcdir} {site} [site2 [site3 ...]]
+    ${PNAME} $(basename "$0") [-e {env-regex}] [-f {local-globs}] [-p] [-r] {srcdir} {site} [site2 [site3 ...]]
 
 DESCRIPTION
     1) The environment list must be in the TGT{env} variable.
@@ -23,28 +27,29 @@ DESCRIPTION
     3) -r option
         Reset files, i.e. deletes them from destination before copying.
     4) -p option
-        Causes pushl to only purge all files in the destination
+        Causes ${PNAME} to only purge all files in the destination
         Usage of -r is redundant here.
 "
 
-# ##############################################################################
-# Globals
-
 export CONN=''
-export CONNOPT=''
-export DESTDIR=''
 export ENVPATHS=''
-export ENVREGEX=''
-export EXCLUDE='@@@@EXCLUDEDUMMY@@@@'
 export GLOBSFINAL=''
-export PURGE_ONLY=false
-export RESET_FILES=''
+
+export DESTDIR=''
 export SRCDIR=''
 
 # ##############################################################################
 # Prep args
 
 # Options:
+
+export CONNOPT=''
+export ENVREGEX=''
+export EXCLUDE='@@@@EXCLUDEDUMMY@@@@'
+export GLOBSOPT=''
+export PURGE_ONLY=false
+export RESET_FILES=''
+
 OPTIND=1
 while getopts ':c:d:e:f:hprx:' opt ; do
     case ${opt} in
@@ -75,7 +80,7 @@ which lftp >/dev/null 2>&1 || exit 10
 prep () {
 
     if ! . "${DS_HOME}/ds.sh" "${DS_HOME}" >/dev/null 2>&1 || [ -z "${DS_LOADED}" ] ; then
-        echo "$(basename "$0"): FATAL: Could not load DS - Daily Shells." 1>&2
+        echo "${PNAME}: FATAL: Could not load DS - Daily Shells." 1>&2
         exit 1
     fi
 
